package com.nelsw;

/**
 * Problem 2 - Even Fibonacci numbers
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * <p>
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * Considering the terms in the Fibonacci sequence whose values do not exceed four million, sum the even-valued terms.
 * <p>
 * <p>
 * The prime factors of 13195 are 5, 7, 13 and 29.
 * <p>
 * What is the largest prime factor of the number 600851475143 ?
 */
public class P2 extends AbstractProblem {

    @Override
    int number() {
        return 2;
    }

    @Override
    Object expected() {
        return 4613732;
    }

    @Override
    Object actual() {
        int a, b = 0, c = 1, sum = 0;
        while (true) {
            a = b;
            b = c;
            c = a + b;
            if (c % 2 == 0) {
                sum += c;
            }
            if (c > Math.pow(10, 6) * 4) {
                return sum;
            }
        }
    }
}
